name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and run VMM examples
    # Don't want any forks or PRs to run this workflow
    if: ${{ github.repository_owner == 'Ivan-Velickovic' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout seL4CP VMM repository
        uses: actions/checkout@v3
      - name: Download seL4CP SDK
        run: ./ci/acquire_sdk.sh sel4cp-sdk.zip ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Extract seL4CP SDK
        run: unzip sel4cp-sdk.zip && tar -xf sel4cp-sdk-1.2.6.tar.gz
      - name: Install VMM dependencies (via apt)
        run: sudo apt update && sudo apt install -y make gcc-aarch64-linux-gnu qemu-system-arm device-tree-compiler expect
      - name: Build and run VMM examples
        run: ./ci/examples.sh sel4cp-sdk-1.2.6
        shell: bash
      - name: Upload built system images
        uses: actions/upload-artifact@v3
        with:
          path: build_*/loader.img
